# -*- coding: utf-8 -*-
"""Problem 5: You are given a list of integers representing the daily temperature (in Celsius) of a city for a month. Your task is to process this data using a single-line list comprehension to generate specific insights..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VaJvoHdvaJfaQcudqFczhfLIfoGUzmgv

# **Problem 5: You are given a list of integers representing the daily temperature (in Celsius) of a city for a month. Your task is to process this data using a single-line list comprehension to generate specific insights.**
"""

temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]

temperatures_above_32 = [temp for temp in temperatures if temp > 32]
print("\n\nTemperatures above 32°C:", temperatures_above_32)

classification = [("Hot", temp) if temp > 35 else ("Warm", temp) if 30 <= temp <= 35 else ("Cool", temp) for temp in temperatures]
print("\n\nTemperature classifications:", classification)


monthly_average = sum(temperatures) / len(temperatures)
temperature_differences = [temp - monthly_average for temp in temperatures]
print("\n\nTemperature differences from monthly average:", temperature_differences)